input_topic: "/mbuggy/os3/points"
output_filtered_topic: "/output/filtered_cloud"
output_noise_topic: "/output/noise_cloud"
leaf_size: 0.01
intensity_min: 0.0
intensity_max: 100.0
min_range: 3.0
max_range: 300.0
noise_mean_k: 78
noise_stddev: 3.8
radius_search: 2.0
min_neighbors: 4
max_iterations: 1000
ground_distance_threshold: 0.1
